[package]
name = "thecat"
version = "0.1.0"
authors = ["M@ <matthew.dunlap+github@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
chrono = "^0"
penrose = {path="../penrose"}
# penrose = {git="https://github.com/sminez/penrose", branch="develop"}
# penrose = "0.1.11"
